x-airflow-common: 
  &airflow-common
  build : ./
  image: ${AIRFLOW_IMAGE_NAME:-extend_airflow:latest}
  environment : &airflow-common-env
    AIRFLOW__CORE__EXECUTOR : LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN : postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND : db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY : "Gp6wDeVXdHtILQx2a85JFpfiKWspnGSt99dIWLeXcWA="
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION : "true"
    AIRFLOW__CORE__LOAD_EXAMPLES : "false"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN : postgresql+psycopg2://airflow:airflow@postgres/airflow
    # AIRFLOW__SMTP__SMTP_HOST : ""
    # AIRFLOW__SMTP__SMTP_PORT : 
    # AIRFLOW__SMTP__SMTP_USER : ""
    # AIRFLOW__SMTP__SMTP_PASSWORD : ""
    # AIRFLOW__SMTP__SMTP_STARTTLS : True
    # AIRFLOW__SMTP__SMTP_SENDER_NAME :
    # AIRFLOW__SMTP__SMTP_MAIL_FROM : 
    # AIRFLOW__SMTP__SMTP_SSL : False
  volumes :
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./logs:/opt/airflow/logs
    - ./dump:/opt/airflow/dump
    - ./airflow.cfg:/opt/airflow/airflow.cfg
  user : "${AIRFLOW_UID:-50000}:0"
  depends_on :
    postgres:
      condition : service_healthy
  networks:
    - airflow-network

services:

  postgres : 
    image : postgres:15
    environment :
      POSTGRES_USER : airflow
      POSTGRES_PASSWORD : airflow
      POSTGRES_DB : airflow
    healthcheck :
      test : ["CMD-SHELL", "pg_isready -U airflow"]
      interval : 5s
      retries : 5
      start_period : 10s
    restart: always
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - airflow-network

  airflow-scheduler : 
    << : *airflow-common
    depends_on :
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    healthcheck :
      test : ["CMD-SHELL", "[ -f /opt/airflow/airflow-scheduler.pid ]"]
      interval : 10s
      timeout : 10s
      retries : 5
    restart: always
    command: scheduler
    networks:
      - airflow-network
    
 
  airflow-webserver : 
    << : *airflow-common
    command : webserver
    depends_on :
      airflow-init:
        condition: service_completed_successfully
    ports :
      - "8082:8080"
    healthcheck :
      test : ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval : 30s
      timeout : 30s
      retries : 3
    restart: always
    networks:
      - airflow-network


  airflow-init : 
    << : *airflow-common
    command : airflow db upgrade
    depends_on :
      postgres:
        condition: service_healthy
    environment :
      << : *airflow-common-env
      _AIRFLOW_DB_MIGRATE : "true"
      _AIRFLOW_WWW_USER_CREATE : "true"
      _AIRFLOW_WWW_USER_USERNAME : ${AIRFLOW_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD : ${AIRFLOW_PASSWORD:-airflow}
    networks:
      - airflow-network

volumes:
  postgres-db-volume:

networks:
  airflow-network:
    driver: bridge


